/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AtmBtn {
        "disabled": boolean;
    }
    interface AtmInput {
        "disabled": boolean;
        "placeholder": string;
        "reset": () => Promise<void>;
    }
    interface MolTransaction {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface AtmInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAtmInputElement;
}
declare global {
    interface HTMLAtmBtnElement extends Components.AtmBtn, HTMLStencilElement {
    }
    var HTMLAtmBtnElement: {
        prototype: HTMLAtmBtnElement;
        new (): HTMLAtmBtnElement;
    };
    interface HTMLAtmInputElement extends Components.AtmInput, HTMLStencilElement {
    }
    var HTMLAtmInputElement: {
        prototype: HTMLAtmInputElement;
        new (): HTMLAtmInputElement;
    };
    interface HTMLMolTransactionElement extends Components.MolTransaction, HTMLStencilElement {
    }
    var HTMLMolTransactionElement: {
        prototype: HTMLMolTransactionElement;
        new (): HTMLMolTransactionElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "atm-btn": HTMLAtmBtnElement;
        "atm-input": HTMLAtmInputElement;
        "mol-transaction": HTMLMolTransactionElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AtmBtn {
        "disabled"?: boolean;
    }
    interface AtmInput {
        "disabled"?: boolean;
        "onInput"?: (event: AtmInputCustomEvent<string>) => void;
        "placeholder"?: string;
    }
    interface MolTransaction {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "atm-btn": AtmBtn;
        "atm-input": AtmInput;
        "mol-transaction": MolTransaction;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "atm-btn": LocalJSX.AtmBtn & JSXBase.HTMLAttributes<HTMLAtmBtnElement>;
            "atm-input": LocalJSX.AtmInput & JSXBase.HTMLAttributes<HTMLAtmInputElement>;
            "mol-transaction": LocalJSX.MolTransaction & JSXBase.HTMLAttributes<HTMLMolTransactionElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
